//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFee
    {
        public int FeesId { get; set; }
        public int RollNo { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> SchoolFee { get; set; }
        public Nullable<decimal> HostelFee { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public bool IsDeleted { get; set; }
        public int StudentId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
